//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentsMaster
    {
        public int ID { get; set; }
        public string Subject { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StDt { get; set; }
        public string StTime { get; set; }
        public Nullable<System.DateTime> EndDt { get; set; }
        public string EndTime { get; set; }
        public string Priority { get; set; }
        public string Reminder { get; set; }
        public Nullable<System.DateTime> ReDate { get; set; }
        public string ReTime { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CompID { get; set; }
    }
}
