//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChallanMaster
    {
        public int CID { get; set; }
        public string ChallanNo { get; set; }
        public Nullable<int> VID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CompID { get; set; }
    }
}
