//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequeReturnMaster
    {
        public int CRID { get; set; }
        public string ClientName { get; set; }
        public string ContactPerson { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> Phone { get; set; }
        public string BankName { get; set; }
        public string BankBranch { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> DepositedDate { get; set; }
        public string Remarks { get; set; }
        public string Action { get; set; }
        public string Attachment { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
