//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CredentialMaster
    {
        public int CrID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string AssignTo { get; set; }
        public string Remarks { get; set; }
        public string URL { get; set; }
        public string Description { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> CompID { get; set; }
    }
}
