//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeVisa
    {
        public int VId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string VisaNo { get; set; }
        public Nullable<int> VisaStatusId { get; set; }
        public Nullable<int> VisaGroupId { get; set; }
        public Nullable<int> VisaTypeId { get; set; }
        public string PlaceOfIssue { get; set; }
        public Nullable<int> IssueCountry { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> ReniewDate { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> EmiratesId { get; set; }
        public Nullable<System.DateTime> EmiratesDate { get; set; }
        public string UID { get; set; }
        public Nullable<int> ComID { get; set; }
        public string Designation { get; set; }
    
        public virtual employee_master employee_master { get; set; }
    }
}
