//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRelative
    {
        public int Id { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string RName { get; set; }
        public string RAddress { get; set; }
        public string RCity { get; set; }
        public string RPhone { get; set; }
        public string REmail { get; set; }
        public string Relation { get; set; }
        public string RMobile { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
