//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDeposite
    {
        public int DepId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string DepDescription { get; set; }
        public Nullable<decimal> DepAmount { get; set; }
        public Nullable<System.DateTime> InvestDate { get; set; }
        public Nullable<System.DateTime> MaturityDate { get; set; }
        public string DepRemarks { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
