//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_master
    {
        public employee_master()
        {
            this.employee_document = new HashSet<employee_document>();
            this.EmployeeQualifications = new HashSet<EmployeeQualification>();
            this.EmployeeQualifications1 = new HashSet<EmployeeQualification>();
            this.EmployeeExperiences = new HashSet<EmployeeExperience>();
            this.EmployeeHealthCards = new HashSet<EmployeeHealthCard>();
            this.EmployeeIncrements = new HashSet<EmployeeIncrement>();
            this.EmployeeLeaves = new HashSet<EmployeeLeave>();
            this.EmployeeOtherDetails = new HashSet<EmployeeOtherDetail>();
            this.EmployeeVisas = new HashSet<EmployeeVisa>();
            this.Other_Expenses = new HashSet<Other_Expenses>();
            this.Petrol_Expense = new HashSet<Petrol_Expense>();
            this.TravelExpences = new HashSet<TravelExpence>();
            this.Vehicle_History = new HashSet<Vehicle_History>();
            this.VehicleMasters = new HashSet<VehicleMaster>();
            this.EmployeePassports = new HashSet<EmployeePassport>();
        }
    
        public int id { get; set; }
        public string Empno { get; set; }
        public string Empname { get; set; }
        public Nullable<int> Compid { get; set; }
        public Nullable<int> Branchid { get; set; }
        public Nullable<int> vcid { get; set; }
        public Nullable<int> vbid { get; set; }
        public string EmployeeType { get; set; }
        public Nullable<int> bloodid { get; set; }
        public string Photo { get; set; }
        public string alias { get; set; }
        public string FileNumber { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public string Category { get; set; }
        public string Mobile { get; set; }
        public string HomeTel { get; set; }
        public string LocalTel { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> DOL { get; set; }
        public Nullable<System.DateTime> RejoinDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Status { get; set; }
        public string Profile { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> JobTitle { get; set; }
        public Nullable<System.DateTime> DOD { get; set; }
        public Nullable<int> WorkingStatus { get; set; }
        public Nullable<decimal> Graduity { get; set; }
    
        public virtual ICollection<employee_document> employee_document { get; set; }
        public virtual ICollection<EmployeeQualification> EmployeeQualifications { get; set; }
        public virtual ICollection<EmployeeQualification> EmployeeQualifications1 { get; set; }
        public virtual ICollection<EmployeeExperience> EmployeeExperiences { get; set; }
        public virtual ICollection<EmployeeHealthCard> EmployeeHealthCards { get; set; }
        public virtual ICollection<EmployeeIncrement> EmployeeIncrements { get; set; }
        public virtual ICollection<EmployeeLeave> EmployeeLeaves { get; set; }
        public virtual ICollection<EmployeeOtherDetail> EmployeeOtherDetails { get; set; }
        public virtual ICollection<EmployeeVisa> EmployeeVisas { get; set; }
        public virtual ICollection<Other_Expenses> Other_Expenses { get; set; }
        public virtual ICollection<Petrol_Expense> Petrol_Expense { get; set; }
        public virtual ICollection<TravelExpence> TravelExpences { get; set; }
        public virtual ICollection<Vehicle_History> Vehicle_History { get; set; }
        public virtual ICollection<VehicleMaster> VehicleMasters { get; set; }
        public virtual ICollection<EmployeePassport> EmployeePassports { get; set; }
    }
}
