//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInsurance
    {
        public int IID { get; set; }
        public Nullable<int> CompID { get; set; }
        public Nullable<int> Branch { get; set; }
        public string Pname { get; set; }
        public Nullable<int> Icomp { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<int> Ptype { get; set; }
        public string Pno { get; set; }
        public string Pamt { get; set; }
        public Nullable<System.DateTime> Pdate { get; set; }
        public Nullable<System.DateTime> PExpDate { get; set; }
        public Nullable<System.DateTime> PremiumDate { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> VID { get; set; }
    
        public virtual Company_master Company_master { get; set; }
        public virtual VehicleMaster VehicleMaster { get; set; }
        public virtual Masters_Tran Masters_Tran { get; set; }
        public virtual Masters_Tran Masters_Tran1 { get; set; }
    }
}
