//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeHealthCard
    {
        public int HId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string Type { get; set; }
        public string CardNo { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string EmiratesID { get; set; }
        public Nullable<System.DateTime> EmiratesExpDate { get; set; }
        public string PersonalNo { get; set; }
    
        public virtual employee_master employee_master { get; set; }
    }
}
