//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePassport
    {
        public int Id { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<int> MasterId { get; set; }
        public Nullable<int> PassportStatusId { get; set; }
        public Nullable<int> PassportID { get; set; }
        public string PassportNo { get; set; }
        public string PlaceIssue { get; set; }
        public Nullable<int> IssueCountry { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> RenewDate { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Nationality { get; set; }
        public string OPassportNo { get; set; }
        public string OPlaceIssue { get; set; }
        public Nullable<int> OIssueCountry { get; set; }
        public Nullable<System.DateTime> OIssueDate { get; set; }
        public Nullable<System.DateTime> OExpiryDate { get; set; }
        public Nullable<System.DateTime> ORenewDate { get; set; }
        public string ORemarks { get; set; }
        public Nullable<int> ONationality { get; set; }
    
        public virtual employee_master employee_master { get; set; }
    }
}
