//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceDocument
    {
        public int Id { get; set; }
        public Nullable<int> VId { get; set; }
        public string FileName { get; set; }
        public string FileUrl { get; set; }
    
        public virtual VehicleMaster VehicleMaster { get; set; }
    }
}
