//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueDetail
    {
        public int IssueId { get; set; }
        public Nullable<int> Cat_id { get; set; }
        public Nullable<int> Item_id { get; set; }
        public Nullable<decimal> IssueQuantity { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string VendorName { get; set; }
        public string InvoiceNo { get; set; }
        public string ChallanNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CompID { get; set; }
    }
}
