//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Master
    {
        public int ItemId { get; set; }
        public Nullable<int> CatId { get; set; }
        public string ItemName { get; set; }
        public string ItemDesc { get; set; }
        public Nullable<decimal> OpStock { get; set; }
        public Nullable<decimal> InwardAmt { get; set; }
        public Nullable<decimal> OutwardAmt { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CompID { get; set; }
    }
}
