//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuTran
    {
        public int MSId { get; set; }
        public Nullable<int> FormId { get; set; }
        public Nullable<int> MHId { get; set; }
        public string Sequence { get; set; }
    
        public virtual FormMaster FormMaster { get; set; }
        public virtual MenuHeaderMaster MenuHeaderMaster { get; set; }
    }
}
