//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollMaster
    {
        public int PId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<int> Days { get; set; }
        public Nullable<decimal> OT { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public int CompId { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public Nullable<int> TotalDays { get; set; }
        public Nullable<decimal> DA { get; set; }
    }
}
