//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Petrol_Card
    {
        public int ID { get; set; }
        public Nullable<int> VID { get; set; }
        public string PetroCardNo { get; set; }
        public Nullable<int> PetrolCardNameID { get; set; }
        public Nullable<int> PaymentModeID { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Status { get; set; }
    
        public virtual Masters_Tran Masters_Tran { get; set; }
        public virtual Masters_Tran Masters_Tran1 { get; set; }
        public virtual VehicleMaster VehicleMaster { get; set; }
    }
}
