//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repayment_Master
    {
        public int Id { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<decimal> Payment { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> CompId { get; set; }
    }
}
