//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenancyMaster
    {
        public TenancyMaster()
        {
            this.TenancyDocuments = new HashSet<TenancyDocument>();
        }
    
        public int TnID { get; set; }
        public string TnNo { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
        public string LandLord { get; set; }
        public string Tn { get; set; }
        public string TnType { get; set; }
        public Nullable<int> TnTypeCompId { get; set; }
        public Nullable<int> TnTypeEmpId { get; set; }
        public Nullable<int> TnTypeId { get; set; }
        public string Others { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Subject { get; set; }
        public string Period { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<decimal> Rent { get; set; }
        public string Terms { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<TenancyDocument> TenancyDocuments { get; set; }
    }
}
