//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade_License
    {
        public int TID { get; set; }
        public string Code { get; set; }
        public string Lno { get; set; }
        public Nullable<int> CompID { get; set; }
        public Nullable<int> EmiratesID { get; set; }
        public Nullable<int> SponsorID { get; set; }
        public Nullable<int> PartnerID { get; set; }
        public Nullable<int> PartnerID2 { get; set; }
        public Nullable<int> PartnerID3 { get; set; }
        public Nullable<int> PartnerID4 { get; set; }
        public Nullable<decimal> Fees { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> LicenseTypeID { get; set; }
    }
}
