//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelExpence
    {
        public int Id { get; set; }
        public Nullable<int> Companyid { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> TFromDate { get; set; }
        public Nullable<System.DateTime> TToDate { get; set; }
        public Nullable<decimal> Fare { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string City { get; set; }
        public Nullable<decimal> AccomodationExp { get; set; }
        public Nullable<decimal> FoodExp { get; set; }
        public Nullable<decimal> Conv_Exp { get; set; }
        public Nullable<decimal> OtherExp { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Company_master Company_master { get; set; }
        public virtual employee_master employee_master { get; set; }
    }
}
