//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle_History
    {
        public int ID { get; set; }
        public Nullable<int> VID { get; set; }
        public Nullable<System.DateTime> From_Date { get; set; }
        public Nullable<System.DateTime> To_Date { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual employee_master employee_master { get; set; }
        public virtual VehicleMaster VehicleMaster { get; set; }
    }
}
