//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleMaster
    {
        public VehicleMaster()
        {
            this.EmployeeInsurances = new HashSet<EmployeeInsurance>();
            this.Petrol_Card = new HashSet<Petrol_Card>();
            this.Petrol_Expense = new HashSet<Petrol_Expense>();
            this.Vehicle_History = new HashSet<Vehicle_History>();
            this.VehicleDocuments = new HashSet<VehicleDocument>();
            this.VehicleRepairings = new HashSet<VehicleRepairing>();
        }
    
        public int VID { get; set; }
        public Nullable<int> CompID { get; set; }
        public string VehicleNo { get; set; }
        public string VehicleName { get; set; }
        public string ModelName { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> Branch_ID { get; set; }
        public string Purchase_Value { get; set; }
        public string Depriciation { get; set; }
        public string CurrentValue { get; set; }
        public string Market_Value { get; set; }
        public Nullable<System.DateTime> Purchased_Date { get; set; }
        public Nullable<System.DateTime> Reg_Date { get; set; }
        public Nullable<System.DateTime> Reg_Exp_Date { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string SalikNo { get; set; }
        public string UsedFor { get; set; }
        public Nullable<decimal> WeightBearCapacity { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> LengthToUse { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> WidthToUse { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> HeightToUse { get; set; }
        public Nullable<int> PermitType { get; set; }
        public string PermitNo { get; set; }
        public Nullable<System.DateTime> PermitExpiryDate { get; set; }
        public Nullable<int> TVStatus { get; set; }
        public string VehicleOwnerName { get; set; }
        public string OwnerAddress { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
    
        public virtual Company_master Company_master { get; set; }
        public virtual employee_master employee_master { get; set; }
        public virtual ICollection<EmployeeInsurance> EmployeeInsurances { get; set; }
        public virtual ICollection<Petrol_Card> Petrol_Card { get; set; }
        public virtual ICollection<Petrol_Expense> Petrol_Expense { get; set; }
        public virtual ICollection<Vehicle_History> Vehicle_History { get; set; }
        public virtual ICollection<VehicleDocument> VehicleDocuments { get; set; }
        public virtual ICollection<VehicleRepairing> VehicleRepairings { get; set; }
    }
}
