//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blood_Group_Master
    {
        public int id { get; set; }
        public string BName { get; set; }
        public string BDescription { get; set; }
        public string BStatus { get; set; }
    }
}
