//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch_master
    {
        public Branch_master()
        {
            this.employee_master = new HashSet<employee_master>();
        }
    
        public int id { get; set; }
        public string Compcode { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string BranchAdd { get; set; }
        public string ContactPerson { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
    
        public virtual ICollection<employee_master> employee_master { get; set; }
    }
}
