//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeave
    {
        public int LID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<System.DateTime> LFrom { get; set; }
        public Nullable<System.DateTime> LTo { get; set; }
        public Nullable<int> LTypeID { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Status { get; set; }
    
        public virtual employee_master employee_master { get; set; }
    }
}
