//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_master
    {
        public employee_master()
        {
            this.EmpDrivingLicences = new HashSet<EmpDrivingLicence>();
            this.employee_document = new HashSet<employee_document>();
            this.EmployeeAbscondings = new HashSet<EmployeeAbsconding>();
            this.EmployeeAllowances = new HashSet<EmployeeAllowance>();
            this.EmployeeContacts = new HashSet<EmployeeContact>();
            this.EmployeeDeposites = new HashSet<EmployeeDeposite>();
            this.EmployeeExperiences = new HashSet<EmployeeExperience>();
            this.EmployeeHealthCards = new HashSet<EmployeeHealthCard>();
            this.EmployeeIncrements = new HashSet<EmployeeIncrement>();
            this.EmployeeLeaves = new HashSet<EmployeeLeave>();
            this.EmployeeOtherDetails = new HashSet<EmployeeOtherDetail>();
            this.EmployeePassports = new HashSet<EmployeePassport>();
            this.EmployeeRelatives = new HashSet<EmployeeRelative>();
            this.Login_Master = new HashSet<Login_Master>();
        }
    
        public int id { get; set; }
        public string Empno { get; set; }
        public string Empname { get; set; }
        public Nullable<int> Compid { get; set; }
        public Nullable<int> Branchid { get; set; }
        public Nullable<int> vcid { get; set; }
        public Nullable<int> vbid { get; set; }
        public string EmployeeType { get; set; }
        public Nullable<int> bloodid { get; set; }
        public string Photo { get; set; }
        public string alias { get; set; }
        public string FileNumber { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public string Category { get; set; }
        public string Mobile { get; set; }
        public string HomeTel { get; set; }
        public string LocalTel { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> DOL { get; set; }
        public Nullable<System.DateTime> RejoinDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Status { get; set; }
        public string Profile { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Branch_master Branch_master { get; set; }
        public virtual Company_master Company_master { get; set; }
        public virtual ICollection<EmpDrivingLicence> EmpDrivingLicences { get; set; }
        public virtual ICollection<employee_document> employee_document { get; set; }
        public virtual ICollection<EmployeeAbsconding> EmployeeAbscondings { get; set; }
        public virtual ICollection<EmployeeAllowance> EmployeeAllowances { get; set; }
        public virtual ICollection<EmployeeContact> EmployeeContacts { get; set; }
        public virtual ICollection<EmployeeDeposite> EmployeeDeposites { get; set; }
        public virtual ICollection<EmployeeExperience> EmployeeExperiences { get; set; }
        public virtual ICollection<EmployeeHealthCard> EmployeeHealthCards { get; set; }
        public virtual ICollection<EmployeeIncrement> EmployeeIncrements { get; set; }
        public virtual ICollection<EmployeeLeave> EmployeeLeaves { get; set; }
        public virtual ICollection<EmployeeOtherDetail> EmployeeOtherDetails { get; set; }
        public virtual ICollection<EmployeePassport> EmployeePassports { get; set; }
        public virtual ICollection<EmployeeRelative> EmployeeRelatives { get; set; }
        public virtual ICollection<Login_Master> Login_Master { get; set; }
    }
}
