//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Blood_Group_Master
{
    public int id { get; set; }
    public string BName { get; set; }
    public string BDescription { get; set; }
    public string BStatus { get; set; }
}

public partial class Branch_master
{
    public Branch_master()
    {
        this.employee_master = new HashSet<employee_master>();
    }

    public int id { get; set; }
    public string Compcode { get; set; }
    public string BranchCode { get; set; }
    public string BranchName { get; set; }
    public string BranchAdd { get; set; }
    public string ContactPerson { get; set; }
    public string Email { get; set; }
    public string Phone { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string Country { get; set; }

    public virtual ICollection<employee_master> employee_master { get; set; }
}

public partial class Company_master
{
    public Company_master()
    {
        this.employee_master = new HashSet<employee_master>();
    }

    public int id { get; set; }
    public string Compcode { get; set; }
    public string CompName { get; set; }
    public string ContactPerson { get; set; }
    public string Email { get; set; }
    public string Phone { get; set; }
    public string Address { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string Country { get; set; }

    public virtual ICollection<employee_master> employee_master { get; set; }
}

public partial class Country
{
    public int Id { get; set; }
    public string Name { get; set; }
    public bool Status { get; set; }
}

public partial class document_category
{
    public int id { get; set; }
    public string category { get; set; }
    public string description { get; set; }
    public int status { get; set; }
}

public partial class EmpDrivingLicence
{
    public int id { get; set; }
    public Nullable<int> EmpId { get; set; }
    public string LicenceNo { get; set; }
    public Nullable<System.DateTime> IssueDate { get; set; }
    public Nullable<System.DateTime> ExpiryDate { get; set; }
    public string IssueCountry { get; set; }
    public string DRemarks { get; set; }
    public string DStatus { get; set; }
    public string CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public string UpdatedBy { get; set; }
    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public virtual employee_master employee_master { get; set; }
}

public partial class employee_document
{
    public int id { get; set; }
    public int empid { get; set; }
    public int categoryid { get; set; }
    public string title { get; set; }
    public string docu_copy { get; set; }

    public virtual employee_master employee_master { get; set; }
}

public partial class employee_master
{
    public employee_master()
    {
        this.EmpDrivingLicences = new HashSet<EmpDrivingLicence>();
        this.employee_document = new HashSet<employee_document>();
        this.EmployeeAbscondings = new HashSet<EmployeeAbsconding>();
        this.EmployeeAllowances = new HashSet<EmployeeAllowance>();
        this.EmployeeContacts = new HashSet<EmployeeContact>();
        this.EmployeeDeposites = new HashSet<EmployeeDeposite>();
        this.EmployeeExperiences = new HashSet<EmployeeExperience>();
        this.EmployeeHealthCards = new HashSet<EmployeeHealthCard>();
        this.EmployeeIncrements = new HashSet<EmployeeIncrement>();
        this.EmployeeLeaves = new HashSet<EmployeeLeave>();
        this.EmployeeOtherDetails = new HashSet<EmployeeOtherDetail>();
        this.EmployeePassports = new HashSet<EmployeePassport>();
        this.EmployeeRelatives = new HashSet<EmployeeRelative>();
        this.Login_Master = new HashSet<Login_Master>();
    }

    public int id { get; set; }
    public string Empno { get; set; }
    public string Empname { get; set; }
    public Nullable<int> Compid { get; set; }
    public Nullable<int> Branchid { get; set; }
    public Nullable<int> vcid { get; set; }
    public Nullable<int> vbid { get; set; }
    public string EmployeeType { get; set; }
    public Nullable<int> bloodid { get; set; }
    public string Photo { get; set; }
    public string alias { get; set; }
    public string FileNumber { get; set; }
    public Nullable<decimal> BasicSalary { get; set; }
    public string Category { get; set; }
    public string Mobile { get; set; }
    public string HomeTel { get; set; }
    public string LocalTel { get; set; }
    public string Email { get; set; }
    public Nullable<System.DateTime> DOJ { get; set; }
    public string Remarks { get; set; }
    public Nullable<System.DateTime> DOL { get; set; }
    public Nullable<System.DateTime> RejoinDate { get; set; }
    public Nullable<System.DateTime> DueDate { get; set; }
    public string Status { get; set; }
    public string Profile { get; set; }
    public string CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public string UpdatedBy { get; set; }
    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public virtual Branch_master Branch_master { get; set; }
    public virtual Company_master Company_master { get; set; }
    public virtual ICollection<EmpDrivingLicence> EmpDrivingLicences { get; set; }
    public virtual ICollection<employee_document> employee_document { get; set; }
    public virtual ICollection<EmployeeAbsconding> EmployeeAbscondings { get; set; }
    public virtual ICollection<EmployeeAllowance> EmployeeAllowances { get; set; }
    public virtual ICollection<EmployeeContact> EmployeeContacts { get; set; }
    public virtual ICollection<EmployeeDeposite> EmployeeDeposites { get; set; }
    public virtual ICollection<EmployeeExperience> EmployeeExperiences { get; set; }
    public virtual ICollection<EmployeeHealthCard> EmployeeHealthCards { get; set; }
    public virtual ICollection<EmployeeIncrement> EmployeeIncrements { get; set; }
    public virtual ICollection<EmployeeLeave> EmployeeLeaves { get; set; }
    public virtual ICollection<EmployeeOtherDetail> EmployeeOtherDetails { get; set; }
    public virtual ICollection<EmployeePassport> EmployeePassports { get; set; }
    public virtual ICollection<EmployeeRelative> EmployeeRelatives { get; set; }
    public virtual ICollection<Login_Master> Login_Master { get; set; }
}

public partial class EmployeeAbsconding
{
    public int AbscId { get; set; }
    public Nullable<int> EmpId { get; set; }
    public string AbscHistory { get; set; }
    public string Remarks { get; set; }
    public string Status { get; set; }
    public string CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public string UpdatedBy { get; set; }
    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public virtual employee_master employee_master { get; set; }
}

public partial class EmployeeAllowance
{
    public int AId { get; set; }
    public Nullable<int> EmpId { get; set; }
    public Nullable<int> AllownaceID { get; set; }
    public Nullable<decimal> Amount { get; set; }
    public string Remarks { get; set; }
    public string Status { get; set; }
    public string CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public string UpdatedBy { get; set; }
    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public virtual employee_master employee_master { get; set; }
}

public partial class EmployeeContact
{
    public int Id { get; set; }
    public Nullable<int> EmpId { get; set; }
    public string Area { get; set; }
    public string Street { get; set; }
    public string City { get; set; }
    public string PoBox { get; set; }
    public string Pincode { get; set; }
    public string State { get; set; }
    public string Country { get; set; }
    public string Fax { get; set; }
    public string Website { get; set; }
    public string Remarks { get; set; }
    public string Status { get; set; }
    public string CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public string UpdatedBy { get; set; }
    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public virtual employee_master employee_master { get; set; }
}

public partial class EmployeeDeposite
{
    public int DepId { get; set; }
    public Nullable<int> EmpId { get; set; }
    public string DepDescription { get; set; }
    public Nullable<decimal> DepAmount { get; set; }
    public Nullable<System.DateTime> InvestDate { get; set; }
    public Nullable<System.DateTime> MaturityDate { get; set; }
    public string DepRemarks { get; set; }
    public string Status { get; set; }
    public string CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public string UpdatedBy { get; set; }
    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public virtual employee_master employee_master { get; set; }
}

public partial class EmployeeExperience
{
    public int ExpId { get; set; }
    public Nullable<int> EmpId { get; set; }
    public string CompName { get; set; }
    public string Address { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string Country { get; set; }
    public string Phone { get; set; }
    public string Mail { get; set; }
    public string ContactPerson { get; set; }
    public string Roles { get; set; }
    public Nullable<System.DateTime> FromDate { get; set; }
    public Nullable<System.DateTime> ToDate { get; set; }
    public string Department { get; set; }
    public string Designation { get; set; }
    public Nullable<decimal> Salary { get; set; }
    public string CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public string UpdatedBy { get; set; }
    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public virtual employee_master employee_master { get; set; }
}

public partial class EmployeeHealthCard
{
    public int HId { get; set; }
    public Nullable<int> EmpId { get; set; }
    public string Type { get; set; }
    public string CardNo { get; set; }
    public Nullable<System.DateTime> IssueDate { get; set; }
    public Nullable<System.DateTime> ExpiryDate { get; set; }
    public string Status { get; set; }
    public string CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public string UpdatedBy { get; set; }
    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public virtual employee_master employee_master { get; set; }
}

public partial class EmployeeIncrement
{
    public int IncId { get; set; }
    public Nullable<int> EmpId { get; set; }
    public Nullable<decimal> IncAmount { get; set; }
    public Nullable<System.DateTime> IncDate { get; set; }
    public string CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public string UpdatedBy { get; set; }
    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public virtual employee_master employee_master { get; set; }
}

public partial class EmployeeLeave
{
    public int LID { get; set; }
    public Nullable<int> EmpID { get; set; }
    public Nullable<System.DateTime> LFrom { get; set; }
    public Nullable<System.DateTime> LTo { get; set; }
    public Nullable<int> LTypeID { get; set; }
    public string Remarks { get; set; }
    public string CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public string UpdatedBy { get; set; }
    public Nullable<System.DateTime> UpdatedDate { get; set; }
    public string Status { get; set; }

    public virtual employee_master employee_master { get; set; }
}

public partial class EmployeeOtherDetail
{
    public int OtherId { get; set; }
    public Nullable<int> EmpId { get; set; }
    public string AwardName { get; set; }
    public string Remarks { get; set; }
    public string Status { get; set; }
    public Nullable<System.DateTime> AwardDate { get; set; }
    public string CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public string UpdatedBy { get; set; }
    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public virtual employee_master employee_master { get; set; }
}

public partial class EmployeePassport
{
    public int Id { get; set; }
    public Nullable<int> EmpId { get; set; }
    public Nullable<int> MasterId { get; set; }
    public Nullable<int> PassportStatusId { get; set; }
    public Nullable<int> PassportID { get; set; }
    public string PassportNo { get; set; }
    public string PlaceIssue { get; set; }
    public string IssueCountry { get; set; }
    public Nullable<System.DateTime> IssueDate { get; set; }
    public Nullable<System.DateTime> ExpiryDate { get; set; }
    public Nullable<System.DateTime> RenewDate { get; set; }
    public string Remarks { get; set; }
    public string Status { get; set; }
    public string CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public string UpdatedBy { get; set; }
    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public virtual employee_master employee_master { get; set; }
}

public partial class EmployeeRelative
{
    public int Id { get; set; }
    public Nullable<int> EmpId { get; set; }
    public string RName { get; set; }
    public string RAddress { get; set; }
    public string RCity { get; set; }
    public string RPhone { get; set; }
    public string REmail { get; set; }
    public string Relation { get; set; }
    public string RMobile { get; set; }
    public string Remarks { get; set; }
    public string Status { get; set; }

    public virtual employee_master employee_master { get; set; }
}

public partial class FormMaster
{
    public FormMaster()
    {
        this.FormMenuTrans = new HashSet<FormMenuTran>();
        this.MenuTrans = new HashSet<MenuTran>();
    }

    public int FormId { get; set; }
    public string FormTitle { get; set; }
    public string FormName { get; set; }
    public string FormUrl { get; set; }
    public string Status { get; set; }

    public virtual ICollection<FormMenuTran> FormMenuTrans { get; set; }
    public virtual ICollection<MenuTran> MenuTrans { get; set; }
}

public partial class FormMenuTran
{
    public int FMTID { get; set; }
    public Nullable<int> FormId { get; set; }
    public Nullable<int> MHID { get; set; }
    public string Sequence { get; set; }

    public virtual FormMaster FormMaster { get; set; }
    public virtual MenuHeaderMaster MenuHeaderMaster { get; set; }
}

public partial class Login_Master
{
    public int UId { get; set; }
    public Nullable<int> RoleID { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }
    public Nullable<int> EmpId { get; set; }
    public string CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public string UpdatedBy { get; set; }
    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public virtual employee_master employee_master { get; set; }
}

public partial class Master
{
    public Master()
    {
        this.Masters_Tran = new HashSet<Masters_Tran>();
    }

    public int MId { get; set; }
    public string MasterType { get; set; }
    public string MasterDesc { get; set; }
    public string MasterCode { get; set; }
    public string CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public string UpdatedBy { get; set; }
    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public virtual ICollection<Masters_Tran> Masters_Tran { get; set; }
}

public partial class Masters_Tran
{
    public int Id { get; set; }
    public string Name { get; set; }
    public Nullable<int> MasterId { get; set; }
    public string Status { get; set; }
    public string CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public string UpdatedBy { get; set; }
    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public virtual Master Master { get; set; }
}

public partial class MenuHeaderMaster
{
    public MenuHeaderMaster()
    {
        this.FormMenuTrans = new HashSet<FormMenuTran>();
        this.MenuTrans = new HashSet<MenuTran>();
    }

    public int MHId { get; set; }
    public string MHName { get; set; }
    public string MHDescription { get; set; }
    public string Icon { get; set; }
    public string Status { get; set; }

    public virtual ICollection<FormMenuTran> FormMenuTrans { get; set; }
    public virtual ICollection<MenuTran> MenuTrans { get; set; }
}

public partial class MenuTran
{
    public int MSId { get; set; }
    public Nullable<int> FormId { get; set; }
    public Nullable<int> MHId { get; set; }
    public string Sequence { get; set; }

    public virtual FormMaster FormMaster { get; set; }
    public virtual MenuHeaderMaster MenuHeaderMaster { get; set; }
}

public partial class WorkHistory
{
    public int Id { get; set; }
    public int EmpId { get; set; }
    public int CompId { get; set; }
    public int BranchId { get; set; }
    public System.DateTime FromDate { get; set; }
    public System.DateTime ToDate { get; set; }
    public int DesignationId { get; set; }
    public string Remarks { get; set; }
    public string Perfomance { get; set; }
    public int CreatedBy { get; set; }
    public System.DateTime CreatedOn { get; set; }
    public Nullable<int> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedOn { get; set; }
}
