//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class EmployeeEntities : DbContext
{
    public EmployeeEntities()
        : base("name=EmployeeEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Blood_Group_Master> Blood_Group_Master { get; set; }
    public DbSet<Branch_master> Branch_master { get; set; }
    public DbSet<Company_master> Company_master { get; set; }
    public DbSet<Country> Countries { get; set; }
    public DbSet<document_category> document_category { get; set; }
    public DbSet<EmpDrivingLicence> EmpDrivingLicences { get; set; }
    public DbSet<employee_document> employee_document { get; set; }
    public DbSet<employee_master> employee_master { get; set; }
    public DbSet<EmployeeAbsconding> EmployeeAbscondings { get; set; }
    public DbSet<EmployeeAllowance> EmployeeAllowances { get; set; }
    public DbSet<EmployeeContact> EmployeeContacts { get; set; }
    public DbSet<EmployeeDeposite> EmployeeDeposites { get; set; }
    public DbSet<EmployeeExperience> EmployeeExperiences { get; set; }
    public DbSet<EmployeeHealthCard> EmployeeHealthCards { get; set; }
    public DbSet<EmployeeIncrement> EmployeeIncrements { get; set; }
    public DbSet<EmployeeLeave> EmployeeLeaves { get; set; }
    public DbSet<EmployeeOtherDetail> EmployeeOtherDetails { get; set; }
    public DbSet<EmployeePassport> EmployeePassports { get; set; }
    public DbSet<EmployeeRelative> EmployeeRelatives { get; set; }
    public DbSet<FormMaster> FormMasters { get; set; }
    public DbSet<FormMenuTran> FormMenuTrans { get; set; }
    public DbSet<Login_Master> Login_Master { get; set; }
    public DbSet<Master> Masters { get; set; }
    public DbSet<Masters_Tran> Masters_Tran { get; set; }
    public DbSet<MenuHeaderMaster> MenuHeaderMasters { get; set; }
    public DbSet<MenuTran> MenuTrans { get; set; }
    public DbSet<WorkHistory> WorkHistories { get; set; }
}
